name: test
on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: dry-run
        default: true
        type: boolean
jobs:
  concatinate:
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@v2
      with:
        ref: main
    - run: cat ta/internal/*.pem > single.pem
