name: test
on:
  workflow_dispatch:
    inputs:
      my_value:
        description: 'My input value'
        required: true
        default: 'foo'
        type: string
jobs:
  concatinate:
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      uses: google-github-actions/auth@v1
    - run: |-
       cat ta/internal/*.pem > single.pem
       wget google.com
