name: test
on:
  workflow_dispatch:
    inputs:
      my_value:
        description: 'My input value'
        required: true
        default: 'foo'
        type: string
jobs:
  initial:
    runs-on: ubuntu-latest
    steps:
    - id: simple
      run: |-
       echo "haa"

  approval:
    needs: initial
    runs-on: ubuntu-latest
    environment: main
    steps:
      - id: ddd
        run: |-
          echo "asdfdf"

    # steps:
    #   - uses: trstringer/manual-approval@v1
    #     with:
    #       secret: ${{ github.TOKEN }}
    #       approvers: selvjith
    #       minimum-approvals: 1
    #       issue-title: "Deploying v1.3.5 to prod from staging"
    #       issue-body: "Please approve or deny the deployment of version v1.3.5."
    #       exclude-workflow-initiator-as-approver: false
    #       additional-approved-words: ''
    #       additional-denied-words: ''

  continue:
    needs: approval
    runs-on: ubuntu-latest
    steps:
      - id: ss
        run: |-
          echo "hee"